//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSIPayroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiometricsLog
    {
        public long ID { get; set; }
        public int BiometricsID { get; set; }
        public System.DateTime DTime { get; set; }
        public int Mode { get; set; }
    }
}
