//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSIPayroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int IncomeID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime PayrollDate { get; set; }
        public decimal Amount { get; set; }
        public decimal NoOfDays { get; set; }
        public System.DateTime StDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<int> PayrollID { get; set; }
        public int Trip { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
