//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSIPayroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.PayrollDetails_Loan = new HashSet<PayrollDetails_Loan>();
        }
    
        public int LoanID { get; set; }
        public int EmployeeID { get; set; }
        public int LoanTypeID { get; set; }
        public System.DateTime StDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int PeriodID { get; set; }
        public decimal PrincipalAmount { get; set; }
        public decimal TotalLoanAmount { get; set; }
        public decimal TotalPayment { get; set; }
        public decimal Amortization { get; set; }
        public Nullable<decimal> LoanBalance { get; set; }
    
        public virtual LoanType LoanType { get; set; }
        public virtual Period Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollDetails_Loan> PayrollDetails_Loan { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
