//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSIPayroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherIncome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtherIncome()
        {
            this.PayrollDetails_OtherIncome = new HashSet<PayrollDetails_OtherIncome>();
        }
    
        public int OtherIncomeID { get; set; }
        public int EmployeeID { get; set; }
        public int IncomeTypeID { get; set; }
        public decimal Amount { get; set; }
        public int PeriodID { get; set; }
        public System.DateTime StDate { get; set; }
        public System.DateTime ToDate { get; set; }
    
        public virtual IncomeType IncomeType { get; set; }
        public virtual Period Period { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollDetails_OtherIncome> PayrollDetails_OtherIncome { get; set; }
    }
}
