//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSIPayroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeType
    {
        public int OvertimeTypeID { get; set; }
        public string OvertimeTypeCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
    }
}
