//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSIPayroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollLogistic
    {
        public int PayrollID { get; set; }
        public Nullable<int> PYTableID { get; set; }
        public int EmployeeID { get; set; }
        public decimal RP1 { get; set; }
        public Nullable<decimal> RP2 { get; set; }
        public Nullable<decimal> NightDifferential { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> Holiday { get; set; }
        public Nullable<decimal> Tardiness { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> OtherIncome { get; set; }
        public decimal Gross { get; set; }
        public Nullable<decimal> PAGIBIG { get; set; }
        public Nullable<decimal> PHILHEALTH { get; set; }
        public Nullable<decimal> SSS { get; set; }
        public Nullable<decimal> Loan { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> Leaves { get; set; }
        public Nullable<decimal> Net { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PYTable PYTable { get; set; }
    }
}
