//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSIPayroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payroll()
        {
            this.PayrollDetails_Deduction = new HashSet<PayrollDetails_Deduction>();
            this.PayrollDetails_Loan = new HashSet<PayrollDetails_Loan>();
            this.Tardies = new HashSet<Tardy>();
            this.Leaves = new HashSet<Leave>();
        }
    
        public int PayrollID { get; set; }
        public Nullable<int> PYTableID { get; set; }
        public int EmployeeID { get; set; }
        public decimal BasicPay { get; set; }
        public decimal Holiday { get; set; }
        public decimal Adjustment { get; set; }
        public decimal Gross { get; set; }
        public decimal Premium { get; set; }
        public decimal Deduction { get; set; }
        public decimal Loan { get; set; }
        public Nullable<decimal> Net { get; set; }
    
        public virtual PYTable PYTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollDetails_Deduction> PayrollDetails_Deduction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollDetails_Loan> PayrollDetails_Loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tardy> Tardies { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
    }
}
