//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSIPayroll.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollDetails_Deduction
    {
        public int PayrollDetails_DeductionID { get; set; }
        public int PayrollID { get; set; }
        public int DeductionID { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Deduction Deduction { get; set; }
        public virtual Payroll Payroll { get; set; }
    }
}
